import { Roboto_Serif } from "next/font/google";
import "./globals.css";
import Provider from "./provider";

const robotoSerif = Roboto_Serif({
  variable: "--font-roboto-serif",
  subsets: ["latin"],
})

export const metadata = {
  title: "Zio Logo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/logo.png" type="image/x-icon" />
        <link rel="apple-touch-icon" href="/logo.png" />
        <meta name="theme-color" content="#ed1e61" />
      </head>
      <body
        className={robotoSerif.className}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
